name: "Build"

concurrency:
  group: "build-${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "gradle.properties"
      - "gradle/**"
      - "plugin/**"
      - "**.gradle.kts"
  push:
    paths:
      - ".github/workflows/**"
      - "gradle.properties"
      - "gradle/**"
      - "plugin/**"
      - "**.gradle.kts"

jobs:
  build:
    name: Build Plugins
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Build plugins
        run: |
          chmod +x ./gradlew
          ./gradlew make

      - name: Upload plugin artifacts
        uses: actions/upload-artifact@v7
        with:
          name: plugins-${{ github.ref_name }}-${{ github.run_number }}
          if-no-files-found: error
          path: plugin/*/build/outputs/*.zip
